LandingPad/Models/LPProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;

namespace LandingPad.Models
{

    [Table("LPProfile")]
    public partial class LPProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LPProfile()
        {
            Pseudonyms = new HashSet<Pseudonym>();
            Writings = new HashSet<Writing>();
            ProfileRoles = new HashSet<ProfileRole>();
            Friends = new HashSet<Friendship>();
            FriendRequestsSent = new HashSet<FriendRequest>();
            FriendRequestsReceived = new HashSet<FriendRequest>();
        }

        [Key]
        public int ProfileID { get; set; }

        public int AccessPermissionID { get; set; }

        public int UserID { get; set; }

        public string LPDescription { get; set; }

        public byte[] ProfilePhoto { get; set; }

        public bool DisplayRealName { get; set; }

        public int? Followers { get; set; }

        public int? Writers { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pseudonym> Pseudonyms { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Writing> Writings { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileRole> ProfileRoles { get; set; }

        [ForeignKey("FirstFriendID")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> Friends { get; set; }

        [ForeignKey("RequesterProfileID")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequest> FriendRequestsSent { get; set; }

        [ForeignKey("RequesteeProfileID")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendRequest> FriendRequestsReceived { get; set; }

        public virtual LPUser LPUser { get; set; }

        public virtual AccessPermission AccessPermission { get; set; }
    }
}

LandingPad/Controllers/LPProfilesController.cs
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LandingPad.DAL;
using LandingPad.Models;
using System.Data.Entity.Infrastructure;
using LandingPad.Repositories;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace LandingPad.Controllers
{
    [RequireHttps]
    [Authorize]
    public class LPProfilesController : AccessController
    {
        private LandingPadContext db = new LandingPadContext();
        ILProfilesRepository lprepo = new LProfilesRepository(new LandingPadContext());

        // GET: LPProfiles

        public ActionResult Index()
        {
            if (!CheckLogin())
            {
                return RedirectToAction("Login", "Account");
            }
            //Get the user's ID
            string uid = GetUserID();
            //Get ASP.NET User Object
            ApplicationUser currentUser = GetUser(uid);
            //Get the LPUser based on ASP.NET User's e-mail
            LPUser lpCurrentUser = GetLPUser(currentUser.Email);
            return View(lprepo.GetAll());
        }

        // GET: LPProfiles/Details/5
        public ActionResult Details()
        {
            if (!CheckLogin())
            {
                return RedirectToAction("Login", "Account");
            }
            //Get the user's ID
            string uid = GetUserID();
            //Get ASP.NET User Object
            ApplicationUser currentUser = GetUser(uid);
            //Get the LPUser based on ASP.NET User's e-mail
            LPUser lpCurrentUser = GetLPUser(currentUser.Email);
            //Get the current user's profile based on the user ID
            LPProfile lPProfile = lprepo.Get(lpCurrentUser.UserID);

            if (lPProfile == null)
            {
                return HttpNotFound();
            }
            return View(lPProfile);
        }

        // GET: LPProfiles/Edit/5
        public ActionResult Edit()
        {
            if (!CheckLogin())
            {
                return RedirectToAction("Login", "Account");
            }
            //Get the user's ID
            string uid = GetUserID();
            //Get ASP.NET User Object
            ApplicationUser currentUser = GetUser(uid);
            //Get the LPUser based on ASP.NET User's e-mail
            LPUser lpCurrentUser = GetLPUser(currentUser.Email);
            LPProfile lPProfile = lprepo.Get(lpCurrentUser.UserID);

            if (lpCurrentUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.LPUsers, "UserID", "Email", lpCurrentUser.UserID);
            return View(lPProfile);
        }

        // POST: LPProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProfileID,UserID,PseudonymID,Birthdate,PhoneNumber,LPDescription,ProfilePhoto,DisplayRealName,Friends,Followers,Writers,Pseudonym")] LPProfile lPProfile)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    //db.Entry(lPProfile).State = EntityState.Modified;
                    lprepo.SetModified(lPProfile);
                    lprepo.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Failed to edit Profile");
            }
            ViewBag.UserID = new SelectList(db.LPUsers, "UserID", "Email", lPProfile.UserID);
            return View(lPProfile);
        }
    }
}

LandingPad/Views/LPProfiles/Details.cshtml
@model LandingPad.Models.LPProfile

@{
    ViewBag.Title = "Profile";
}

<h2>@if (Model.DisplayRealName == false)
{
    @Html.DisplayFor(model => model.LPUser.Username)
}
else
{
    <p>
        @Html.DisplayFor(model => model.LPUser.GivenName)  @Html.DisplayFor(model => model.LPUser.Surname)
    </p>
}
    </h2>

<div>
    <h4>Profile Page</h4>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LPUser.GivenName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LPUser.GivenName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LPUser.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LPUser.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LPUser.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LPUser.Birthdate)
        </dd>

        <dt>
            Age :
        </dt>

        <dd>

            @if (Model.LPUser.Birthdate.HasValue)
            {
                var today = DateTime.Today;
                var age = today.Year - Model.LPUser.Birthdate.Value.Year;
                if (Model.LPUser.Birthdate > today.AddYears(-age))
                {
                    age--;
                }
                <span>@age </span>
            }

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LPUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LPUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LPDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LPDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Friends)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Friends)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Followers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Followers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writers)
        </dd>

    
    <dt>
        Current @Html.DisplayNameFor(model => model.Pseudonyms)
    </dt>
        <th>:</th>
    @foreach (var item in Model.Pseudonyms)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Pseudonym1)
            </td>
        </tr>
    }
        </dl>
</div>

LandingPad/Views/LPProfiles/Edit.cshtml
@model LandingPad.Models.LPProfile


@{
    ViewBag.Title = "Settings";
    Model.LPUser.Birthdate = DateTime.Now;
}

<h2>Profile Settings</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProfileID)
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.LPUser.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LPUser.Username)
                @Html.ValidationMessageFor(model => model.LPUser.Username)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LPUser.GivenName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LPUser.GivenName)
                @Html.ValidationMessageFor(model => model.LPUser.GivenName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LPUser.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LPUser.Surname)
                @Html.ValidationMessageFor(model => model.LPUser.Surname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LPUser.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LPUser.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LPUser.Birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.LPDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LPDescription)
                @Html.ValidationMessageFor(model => model.LPDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilePhoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfilePhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisplayRealName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DisplayRealName)
                    @Html.ValidationMessageFor(model => model.DisplayRealName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Friends, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Friends, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Friends, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Followers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Followers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Followers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>
    <button>
        @Html.ActionLink("Back", "Details", "LPProfiles")
    </button>
</p>

LandingPad/Views/LPProfiles/Index.cshtml
@model IEnumerable<LandingPad.Models.LPProfile>


@{
    ViewBag.Title = "Profile";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LPUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfilePhoto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Friends)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Followers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Writers)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LPUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProfilePhoto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Friends)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Followers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Writers)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProfileID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ProfileID })
        </td>
    </tr>
}

</table>